/// Container table for dashboard HTML content measures
table _Dashboard
	lineageTag: b622798d-526b-495e-af61-21e26dffdfe0

	/// Overview KPI cards row
	measure 'HTML - KPI Cards' = "<style>*{box-sizing:border-box;margin:0;padding:0;font-family:sans-serif}.wrap{padding:12px}.sec{font-size:10px;font-weight:600;color:#999;letter-spacing:.07em;text-transform:uppercase;margin-bottom:10px}.grid{display:grid;grid-template-columns:repeat(7,1fr);gap:8px}.kpi{background:#fff;border:1px solid #ebebeb;border-radius:8px;padding:11px 13px}.kl{font-size:10px;color:#aaa;margin-bottom:5px;text-transform:uppercase;letter-spacing:.05em}.kv{font-size:21px;font-weight:500;color:#111;line-height:1}.ks{font-size:10px;color:#bbb;margin-top:3px}</style><div class='wrap'><div class='sec'>Overview</div><div class='grid'><div class='kpi'><div class='kl'>Total views</div><div class='kv'>20.8M</div><div class='ks'>12 channels</div></div><div class='kpi'><div class='kl'>Total videos</div><div class='kv'>764</div><div class='ks'>all channels</div></div><div class='kpi'><div class='kl'>Total likes</div><div class='kv'>277K</div></div><div class='kpi'><div class='kl'>Subscribers</div><div class='kv'>49.9K</div><div class='ks'>net gain</div></div><div class='kpi'><div class='kl'>Impressions</div><div class='kv'>289M</div></div><div class='kpi'><div class='kl'>Avg CTR</div><div class='kv'>3.6%</div><div class='ks'>across channels</div></div><div class='kpi'><div class='kl'>Avg watch time</div><div class='kv'>21.7</div><div class='ks'>min / view</div></div></div></div>"
		formatString: @
		lineageTag: 94dbd07b-bcf7-420a-9d4f-5e02c69f78ba

	/// Horizontal CSS bar chart of views by channel
	measure 'HTML - Channel Views' = "<style>*{box-sizing:border-box;margin:0;padding:0;font-family:sans-serif}.wrap{padding:12px}.sec{font-size:10px;font-weight:600;color:#999;letter-spacing:.07em;text-transform:uppercase;margin-bottom:10px}.cols{display:grid;grid-template-columns:1fr 1fr;gap:14px}.card{background:#fff;border:1px solid #ebebeb;border-radius:10px;padding:14px 16px}.title{font-size:12px;font-weight:500;color:#555;margin-bottom:14px}.legend{display:flex;gap:14px;font-size:10px;color:#888;margin-bottom:10px}.dot{width:8px;height:8px;border-radius:2px;display:inline-block;margin-right:3px}.row{display:flex;align-items:center;gap:8px;margin-bottom:6px}.lbl{font-size:11px;color:#777;width:46px;flex-shrink:0;text-align:right}.track{flex:1;background:#f0f0ee;border-radius:3px;height:14px}.fill{height:14px;border-radius:3px;background:#378ADD;min-width:2px}.val{font-size:10px;color:#999;width:38px;flex-shrink:0}.bars{flex:1;display:flex;flex-direction:column;gap:3px}.th{height:9px}.fill-g{height:9px;border-radius:3px;background:#1D9E75;min-width:2px}.fill-r{height:9px;border-radius:3px;background:#D85A30;min-width:2px}.val2{font-size:10px;color:#aaa;width:58px;flex-shrink:0;text-align:right}</style>" & "<div class='wrap'><div class='sec'>Channel performance</div><div class='cols'>" & "<div class='card'><div class='title'>Total views by channel</div>" & "<div class='row'><div class='lbl'>ch_007</div><div class='track'><div class='fill' style='width:100%'></div></div><div class='val'>9.44M</div></div>" & "<div class='row'><div class='lbl'>ch_008</div><div class='track'><div class='fill' style='width:53.8%'></div></div><div class='val'>5.08M</div></div>" & "<div class='row'><div class='lbl'>ch_006</div><div class='track'><div class='fill' style='width:22.7%'></div></div><div class='val'>2.14M</div></div>" & "<div class='row'><div class='lbl'>ch_002</div><div class='track'><div class='fill' style='width:18.7%'></div></div><div class='val'>1.77M</div></div>" & "<div class='row'><div class='lbl'>ch_001</div><div class='track'><div class='fill' style='width:5.0%'></div></div><div class='val'>475K</div></div>" & "<div class='row'><div class='lbl'>ch_009</div><div class='track'><div class='fill' style='width:4.5%'></div></div><div class='val'>421K</div></div>" & "<div class='row'><div class='lbl'>ch_003</div><div class='track'><div class='fill' style='width:3.6%'></div></div><div class='val'>344K</div></div>" & "<div class='row'><div class='lbl'>ch_005</div><div class='track'><div class='fill' style='width:1.5%'></div></div><div class='val'>143K</div></div>" & "<div class='row'><div class='lbl'>ch_004</div><div class='track'><div class='fill' style='width:0.27%'></div></div><div class='val'>25.6K</div></div>" & "<div class='row'><div class='lbl'>ch_010</div><div class='track'><div class='fill' style='width:0.05%'></div></div><div class='val'>4.5K</div></div></div>" & "<div class='card'><div class='title'>Avg CTR vs like rate by channel</div><div class='legend'><span><span class='dot' style='background:#1D9E75'></span>Avg CTR %</span><span><span class='dot' style='background:#D85A30'></span>Like rate %</span></div>" & "<div class='row'><div class='lbl'>ch_007</div><div class='bars'><div class='th'><div class='fill-g' style='width:43.9%'></div></div><div class='th'><div class='fill-r' style='width:29.8%'></div></div></div><div class='val2'>2.61 / 1.77</div></div>" & "<div class='row'><div class='lbl'>ch_008</div><div class='bars'><div class='th'><div class='fill-g' style='width:34.8%'></div></div><div class='th'><div class='fill-r' style='width:18.7%'></div></div></div><div class='val2'>2.07 / 1.11</div></div>" & "<div class='row'><div class='lbl'>ch_006</div><div class='bars'><div class='th'><div class='fill-g' style='width:82.0%'></div></div><div class='th'><div class='fill-r' style='width:16.0%'></div></div></div><div class='val2'>4.87 / 0.95</div></div>" & "<div class='row'><div class='lbl'>ch_002</div><div class='bars'><div class='th'><div class='fill-g' style='width:51.3%'></div></div><div class='th'><div class='fill-r' style='width:18.2%'></div></div></div><div class='val2'>3.05 / 1.08</div></div>" & "<div class='row'><div class='lbl'>ch_001</div><div class='bars'><div class='th'><div class='fill-g' style='width:81.7%'></div></div><div class='th'><div class='fill-r' style='width:14.1%'></div></div></div><div class='val2'>4.85 / 0.84</div></div>" & "<div class='row'><div class='lbl'>ch_009</div><div class='bars'><div class='th'><div class='fill-g' style='width:63.4%'></div></div><div class='th'><div class='fill-r' style='width:14.5%'></div></div></div><div class='val2'>3.77 / 0.86</div></div>" & "<div class='row'><div class='lbl'>ch_003</div><div class='bars'><div class='th'><div class='fill-g' style='width:53.7%'></div></div><div class='th'><div class='fill-r' style='width:24.2%'></div></div></div><div class='val2'>3.19 / 1.44</div></div>" & "<div class='row'><div class='lbl'>ch_005</div><div class='bars'><div class='th'><div class='fill-g' style='width:58.5%'></div></div><div class='th'><div class='fill-r' style='width:20.7%'></div></div></div><div class='val2'>3.48 / 1.23</div></div>" & "<div class='row'><div class='lbl'>ch_004</div><div class='bars'><div class='th'><div class='fill-g' style='width:78.4%'></div></div><div class='th'><div class='fill-r' style='width:20.0%'></div></div></div><div class='val2'>4.66 / 1.19</div></div>" & "<div class='row'><div class='lbl'>ch_010</div><div class='bars'><div class='th'><div class='fill-g' style='width:100%'></div></div><div class='th'><div class='fill-r' style='width:23.7%'></div></div></div><div class='val2'>5.94 / 1.41</div></div></div></div></div>"
		formatString: @
		lineageTag: 95982263-8ad1-4167-8dcb-48b4424a5884

	/// Stacked CSS bar chart of monthly views by category
	measure 'HTML - Category Trends' = "<style>*{box-sizing:border-box;margin:0;padding:0;font-family:sans-serif}.wrap{padding:12px}.sec{font-size:10px;font-weight:600;color:#999;letter-spacing:.07em;text-transform:uppercase;margin-bottom:10px}.cols{display:grid;grid-template-columns:1fr 1fr;gap:14px}.card{background:#fff;border:1px solid #ebebeb;border-radius:10px;padding:14px 16px}.title{font-size:12px;font-weight:500;color:#555;margin-bottom:8px}.legend{display:flex;flex-wrap:wrap;gap:8px;font-size:10px;color:#888;margin-bottom:12px}.dot{width:8px;height:8px;border-radius:2px;display:inline-block;margin-right:3px}.months{display:grid;grid-template-columns:repeat(5,1fr);gap:8px;align-items:end}.mcol{display:flex;flex-direction:column;align-items:center}.stack{display:flex;flex-direction:column;justify-content:flex-end;width:100%;height:160px;border-radius:4px 4px 0 0;overflow:hidden}.seg{width:100%}.mlbl{font-size:9px;color:#aaa;margin-top:5px;text-align:center}.mtot{font-size:9px;color:#bbb;margin-bottom:3px}.donut-wrap{display:flex;align-items:center;gap:20px;margin-top:8px}.donut{width:110px;height:110px;border-radius:50%;flex-shrink:0;background:conic-gradient(#378ADD 0% 54.2%,#1D9E75 54.2% 79.9%,#7F77DD 79.9% 90.7%,#D85A30 90.7% 98.0%,#BA7517 98.0% 100%);position:relative}.hole{position:absolute;inset:0;margin:auto;width:60px;height:60px;background:#fff;border-radius:50%;top:50%;left:50%;transform:translate(-50%,-50%)}.legs{display:flex;flex-direction:column;gap:7px}.leg{display:flex;align-items:center;gap:7px;font-size:11px;color:#555}.pct{font-size:10px;color:#aaa;margin-left:auto;padding-left:8px}</style>" & "<div class='wrap'><div class='sec'>Category trends</div><div class='cols'>" & "<div class='card'><div class='title'>Monthly views by category</div><div class='legend'><span><span class='dot' style='background:#378ADD'></span>Education</span><span><span class='dot' style='background:#1D9E75'></span>Science &amp; Tech</span><span><span class='dot' style='background:#D85A30'></span>Entertainment</span><span><span class='dot' style='background:#BA7517'></span>People &amp; Blogs</span><span><span class='dot' style='background:#7F77DD'></span>Sports</span></div>" & "<div class='months'>" & "<div class='mcol'><div class='mtot'>40.7K</div><div class='stack'><div class='seg' style='background:#7F77DD;height:0%'></div><div class='seg' style='background:#BA7517;height:0%'></div><div class='seg' style='background:#D85A30;height:0%'></div><div class='seg' style='background:#1D9E75;height:100%'></div><div class='seg' style='background:#378ADD;height:0%'></div></div><div class='mlbl'>Oct 25</div></div>" & "<div class='mcol'><div class='mtot'>7.4K</div><div class='stack'><div class='seg' style='background:#7F77DD;height:0%'></div><div class='seg' style='background:#BA7517;height:0%'></div><div class='seg' style='background:#D85A30;height:0%'></div><div class='seg' style='background:#1D9E75;height:100%'></div><div class='seg' style='background:#378ADD;height:0%'></div></div><div class='mlbl'>Nov 25</div></div>" & "<div class='mcol'><div class='mtot'>6.74M</div><div class='stack'><div class='seg' style='background:#7F77DD;height:5.97%'></div><div class='seg' style='background:#BA7517;height:1.18%'></div><div class='seg' style='background:#D85A30;height:5.18%'></div><div class='seg' style='background:#1D9E75;height:32.05%'></div><div class='seg' style='background:#378ADD;height:55.65%'></div></div><div class='mlbl'>Jan 26</div></div>" & "<div class='mcol'><div class='mtot'>5.86M</div><div class='stack'><div class='seg' style='background:#7F77DD;height:9.05%'></div><div class='seg' style='background:#BA7517;height:1.62%'></div><div class='seg' style='background:#D85A30;height:7.25%'></div><div class='seg' style='background:#1D9E75;height:27.52%'></div><div class='seg' style='background:#378ADD;height:53.53%'></div></div><div class='mlbl'>Feb 26</div></div>" & "<div class='mcol'><div class='mtot'>7.27M</div><div class='stack'><div class='seg' style='background:#7F77DD;height:16.66%'></div><div class='seg' style='background:#BA7517;height:3.45%'></div><div class='seg' style='background:#D85A30;height:9.45%'></div><div class='seg' style='background:#1D9E75;height:17.48%'></div><div class='seg' style='background:#378ADD;height:52.92%'></div></div><div class='mlbl'>Mar 26</div></div>" & "</div></div>" & "<div class='card'><div class='title'>View share by category</div><div class='donut-wrap'><div class='donut'><div class='hole'></div></div><div class='legs'><div class='leg'><div class='dot' style='background:#378ADD'></div>Education<span class='pct'>54.2%</span></div><div class='leg'><div class='dot' style='background:#1D9E75'></div>Science &amp; Tech<span class='pct'>25.7%</span></div><div class='leg'><div class='dot' style='background:#7F77DD'></div>Sports<span class='pct'>10.8%</span></div><div class='leg'><div class='dot' style='background:#D85A30'></div>Entertainment<span class='pct'>7.4%</span></div><div class='leg'><div class='dot' style='background:#BA7517'></div>People &amp; Blogs<span class='pct'>2.1%</span></div></div></div></div>" & "</div></div>"
		formatString: @
		lineageTag: 856c1b2e-9dd6-44bb-877a-43ed9ba96dd5

	/// CSS grouped bars comparing long-form vs short-form views per category
	measure 'HTML - Long vs Short Form' = "<style>*{box-sizing:border-box;margin:0;padding:0;font-family:sans-serif}.wrap{padding:12px}.sec{font-size:10px;font-weight:600;color:#999;letter-spacing:.07em;text-transform:uppercase;margin-bottom:10px}.cols{display:grid;grid-template-columns:1fr 1fr;gap:14px}.card{background:#fff;border:1px solid #ebebeb;border-radius:10px;padding:14px 16px}.title{font-size:12px;font-weight:500;color:#555;margin-bottom:8px}.legend{display:flex;gap:14px;font-size:10px;color:#888;margin-bottom:12px}.dot{width:8px;height:8px;border-radius:2px;display:inline-block;margin-right:3px}.row{display:flex;align-items:center;gap:8px;margin-bottom:7px}.lbl{font-size:11px;color:#777;width:88px;flex-shrink:0;text-align:right}.bars{flex:1;display:flex;flex-direction:column;gap:3px}.th{height:9px;background:#f0f0ee;border-radius:3px}.fill-b{height:9px;border-radius:3px;background:#378ADD;min-width:2px}.fill-a{height:9px;border-radius:3px;background:#EF9F27;min-width:0}.val{font-size:10px;color:#aaa;width:70px;flex-shrink:0;text-align:right}table{width:100%;border-collapse:collapse;font-size:12px}th{font-size:10px;font-weight:600;color:#bbb;text-align:left;padding:5px 8px;border-bottom:1px solid #f0f0ee;text-transform:uppercase;letter-spacing:.04em}td{padding:6px 8px;border-bottom:1px solid #f8f8f6;color:#333}.pill{font-size:10px;background:#f3f3f1;padding:2px 7px;border-radius:4px;color:#666}.ch{color:#aaa}.bwrap{display:flex;align-items:center;gap:5px}.bar{height:4px;border-radius:2px;background:#378ADD;display:inline-block}</style>" & "<div class='wrap'><div class='sec'>Breakdown &amp; top videos</div><div class='cols'>" & "<div class='card'><div class='title'>Long-form vs short-form views</div><div class='legend'><span><span class='dot' style='background:#378ADD'></span>Long-form</span><span><span class='dot' style='background:#EF9F27'></span>Short-form</span></div>" & "<div class='row'><div class='lbl'>Education</div><div class='bars'><div class='th'><div class='fill-b' style='width:100%'></div></div><div class='th'><div class='fill-a' style='width:0.1%'></div></div></div><div class='val'>10.7M / 10.8K</div></div>" & "<div class='row'><div class='lbl'>Science &amp; Tech</div><div class='bars'><div class='th'><div class='fill-b' style='width:37.4%'></div></div><div class='th'><div class='fill-a' style='width:100%'></div></div></div><div class='val'>4.0M / 1.07M</div></div>" & "<div class='row'><div class='lbl'>Entertainment</div><div class='bars'><div class='th'><div class='fill-b' style='width:13.6%'></div></div><div class='th'><div class='fill-a' style='width:0%'></div></div></div><div class='val'>1.46M / 0</div></div>" & "<div class='row'><div class='lbl'>People &amp; Blogs</div><div class='bars'><div class='th'><div class='fill-b' style='width:3.9%'></div></div><div class='th'><div class='fill-a' style='width:0.02%'></div></div></div><div class='val'>423K / 2.1K</div></div>" & "<div class='row'><div class='lbl'>Sports</div><div class='bars'><div class='th'><div class='fill-b' style='width:17.7%'></div></div><div class='th'><div class='fill-a' style='width:2.3%'></div></div></div><div class='val'>1.9M / 243K</div></div></div>" & "<div class='card'><div class='title'>Top videos by views</div><table><thead><tr><th>Title</th><th>Channel</th><th>Category</th><th>Views</th><th>CTR</th></tr></thead><tbody>" & "<tr><td>Video 0626</td><td class='ch'>ch_008</td><td><span class='pill'>Sci &amp; Tech</span></td><td><div class='bwrap'><div class='bar' style='width:60px'></div>98.0K</div></td><td>3.64%</td></tr>" & "<tr><td>Video 0075</td><td class='ch'>ch_002</td><td><span class='pill'>Education</span></td><td><div class='bwrap'><div class='bar' style='width:1px'></div>986</div></td><td>1.35%</td></tr>" & "<tr><td>Video 0688</td><td class='ch'>&mdash;</td><td><span class='pill'>Entertainment</span></td><td><div class='bwrap'><div class='bar' style='width:1px'></div>982</div></td><td>2.61%</td></tr>" & "<tr><td>Video 0297</td><td class='ch'>ch_009</td><td><span class='pill'>People</span></td><td><div class='bwrap'><div class='bar' style='width:1px'></div>99</div></td><td>2.35%</td></tr>" & "<tr><td>Video 0260</td><td class='ch'>ch_004</td><td><span class='pill'>Education</span></td><td><div class='bwrap'><div class='bar' style='width:1px'></div>98</div></td><td>2.90%</td></tr>" & "</tbody></table></div></div></div>"
		formatString: @
		lineageTag: e2b657fc-a2cd-4edc-ba92-b1e2862630a0

	/// Full dashboard combining all HTML section measures into one
	measure 'HTML - Full Dashboard' = [HTML - KPI Cards] & [HTML - Channel Views] & [HTML - Category Trends] & [HTML - Long vs Short Form]
		formatString: @
		lineageTag: 5f13ac09-ea5e-494f-9501-49b1fde20528

	column x
		lineageTag: c2765230-e7aa-4525-8410-1bf12758af66
		isNameInferred
		sourceColumn: [x]

	partition _Dashboard = calculated
		mode: import
		source = ROW("x", BLANK())

